export type BlogPost = {
  slug: string
  title: string
  subtitle: string
  category: string
  icon: string
  readTime: number
  description: string
  tags: string[]
}

export const CATEGORIES = [
  'Getting Started',
  'Core Features',
  'AI Tools',
  'Growth',
  'Analytics & Reports',
  'Settings & Config',
  'Agency',
]

export const POSTS: BlogPost[] = [
  // ── Getting Started ──────────────────────────────────────────────────────────
  {
    slug: 'getting-started',
    title: 'Getting Started with CooVex',
    subtitle: 'Set up your AI business agent in 5 minutes',
    category: 'Getting Started',
    icon: '🚀',
    readTime: 5,
    description: 'Learn how to connect your business, add competitors, and get your first AI briefing. Complete setup guide.',
    tags: ['onboarding', 'setup', 'quickstart'],
  },
  {
    slug: 'dashboard-agent-inbox',
    title: 'Dashboard & Agent Inbox',
    subtitle: 'Your daily command center for business intelligence',
    category: 'Getting Started',
    icon: '📡',
    readTime: 4,
    description: 'Understand how to read your daily briefing, act on agent signals, and interpret your Business Health Score.',
    tags: ['dashboard', 'inbox', 'signals', 'health-score'],
  },
  {
    slug: 'agent-report',
    title: 'Daily Agent Report',
    subtitle: 'Your personalized AI-generated business report every morning',
    category: 'Getting Started',
    icon: '📋',
    readTime: 3,
    description: 'Learn how to read, customize, and act on the Daily Agent Report — a full briefing generated each morning by your AI agent.',
    tags: ['agent', 'report', 'briefing', 'daily'],
  },
  {
    slug: 'notifications',
    title: 'Notifications & Alerts',
    subtitle: 'Get notified the moment something important happens',
    category: 'Getting Started',
    icon: '🔔',
    readTime: 3,
    description: 'Configure real-time alerts for competitor moves, new reviews, goal risks, and lead activity. Set thresholds, channels (email/Slack), and quiet hours.',
    tags: ['notifications', 'alerts', 'email', 'slack'],
  },

  // ── Core Features ────────────────────────────────────────────────────────────
  {
    slug: 'website-audit',
    title: 'Website Audit',
    subtitle: 'Get an AI-powered full audit of your website',
    category: 'Core Features',
    icon: '🔍',
    readTime: 6,
    description: 'Run a complete SEO, speed, mobile, and trust audit. Learn how to read results and execute the AI action plan.',
    tags: ['audit', 'seo', 'website', 'performance'],
  },
  {
    slug: 'content-calendar',
    title: 'Content Calendar',
    subtitle: 'Let AI write, schedule, and track your social posts',
    category: 'Core Features',
    icon: '✍️',
    readTime: 5,
    description: 'Learn how to generate posts, schedule them, and analyze performance. Works with LinkedIn, Facebook, and Instagram.',
    tags: ['content', 'social-media', 'posts', 'scheduling'],
  },
  {
    slug: 'content-performance',
    title: 'Content Performance',
    subtitle: 'Track which posts drive engagement and leads',
    category: 'Core Features',
    icon: '📊',
    readTime: 4,
    description: 'Analyze reach, engagement rate, clicks, and conversions for every post. Identify your best-performing content types and optimal posting times.',
    tags: ['content', 'performance', 'analytics', 'engagement'],
  },
  {
    slug: 'lead-management',
    title: 'Lead Management & Scoring',
    subtitle: 'AI scores every lead so you know who to call first',
    category: 'Core Features',
    icon: '🎯',
    readTime: 6,
    description: 'Add leads, understand AI scores (0–100), run drip campaigns, and track deals through your pipeline.',
    tags: ['leads', 'scoring', 'pipeline', 'crm'],
  },
  {
    slug: 'lead-funnel',
    title: 'Lead Funnel',
    subtitle: 'See exactly where leads drop off and how to fix it',
    category: 'Core Features',
    icon: '🔻',
    readTime: 4,
    description: 'The Lead Funnel view shows conversion rates between every pipeline stage. Identify bottlenecks and get AI recommendations to improve them.',
    tags: ['funnel', 'pipeline', 'conversion', 'leads'],
  },
  {
    slug: 'cold-leads',
    title: 'Cold Lead Nurturing',
    subtitle: 'Revive cold leads with automated AI sequences',
    category: 'Core Features',
    icon: '🧊',
    readTime: 4,
    description: 'Manage leads scored below 40. Set up cold nurture drip sequences and track re-engagement. Know when a cold lead heats back up.',
    tags: ['cold-leads', 'nurture', 'drip', 're-engagement'],
  },
  {
    slug: 'find-leads',
    title: 'Lead Finder',
    subtitle: 'AI finds potential leads in your target market',
    category: 'Core Features',
    icon: '🔎',
    readTime: 4,
    description: 'Use the Lead Finder to discover businesses and contacts that match your ideal customer profile. Filter by industry, size, location, and signals.',
    tags: ['leads', 'prospecting', 'finder', 'outbound'],
  },
  {
    slug: 'competitor-tracking',
    title: 'Competitor Tracking',
    subtitle: 'Monitor up to 50 competitors — automatically',
    category: 'Core Features',
    icon: '🏆',
    readTime: 5,
    description: 'Add competitors, track pricing and reviews, get instant alerts on moves, and benchmark your position.',
    tags: ['competitors', 'intelligence', 'benchmarking'],
  },
  {
    slug: 'competitor-benchmark',
    title: 'Competitor Benchmark',
    subtitle: 'Side-by-side comparison across 15 dimensions',
    category: 'Core Features',
    icon: '⚖️',
    readTime: 4,
    description: 'Compare your business against every competitor across reviews, content, pricing, digital presence, and health score. Spot gaps and advantages instantly.',
    tags: ['benchmark', 'competitors', 'comparison', 'analysis'],
  },
  {
    slug: 'review-management',
    title: 'Review Management',
    subtitle: 'Never leave a review unanswered again',
    category: 'Core Features',
    icon: '⭐',
    readTime: 4,
    description: 'Connect your review sources, use AI-generated responses, track rating trends, and compare against competitors.',
    tags: ['reviews', 'reputation', 'google', 'feedback'],
  },
  {
    slug: 'app-store-reviews',
    title: 'App Store Reviews',
    subtitle: 'Manage iOS and Android reviews from one place',
    category: 'Core Features',
    icon: '📱',
    readTime: 3,
    description: 'Connect your App Store and Google Play listings. Get AI draft responses for every review, track rating trends, and respond faster than competitors.',
    tags: ['app-store', 'reviews', 'ios', 'android'],
  },
  {
    slug: 'products',
    title: 'Products & Services',
    subtitle: 'Track your product portfolio and pricing',
    category: 'Core Features',
    icon: '📦',
    readTime: 3,
    description: 'Manage your products and services catalog. Link products to leads, proposals, and revenue tracking for full business visibility.',
    tags: ['products', 'services', 'catalog', 'pricing'],
  },
  {
    slug: 'trends',
    title: 'Trends & Industry Intelligence',
    subtitle: 'Stay ahead with AI-curated trend alerts',
    category: 'Core Features',
    icon: '📡',
    readTime: 3,
    description: 'Use the Trends feed to spot viral hashtags, industry news, and emerging opportunities before your competitors do.',
    tags: ['trends', 'intelligence', 'industry', 'news'],
  },
  {
    slug: 'integrations',
    title: 'Integrations',
    subtitle: 'Connect your CRM, social, and business tools',
    category: 'Core Features',
    icon: '🔗',
    readTime: 5,
    description: 'Step-by-step guides for connecting HubSpot, Salesforce, LinkedIn, Google Analytics, and 20+ more tools.',
    tags: ['integrations', 'crm', 'hubspot', 'salesforce'],
  },

  // ── AI Tools ─────────────────────────────────────────────────────────────────
  {
    slug: 'ai-coach',
    title: 'AI Coach Chat',
    subtitle: 'Ask your AI agent anything about your business',
    category: 'AI Tools',
    icon: '💬',
    readTime: 4,
    description: 'Learn to use the AI Coach to diagnose problems, brainstorm ideas, write copy, and get strategic advice.',
    tags: ['ai', 'coach', 'chat', 'strategy'],
  },
  {
    slug: 'chatbot',
    title: 'AI Chatbot Builder',
    subtitle: 'Build a customer-facing AI chatbot for your website',
    category: 'AI Tools',
    icon: '🤖',
    readTime: 5,
    description: 'Create and train an AI chatbot that answers customer questions using your business data. Embed it on your website in minutes.',
    tags: ['chatbot', 'customer-service', 'embed', 'ai'],
  },
  {
    slug: 'business-plan',
    title: 'AI Business Plan Generator',
    subtitle: 'Generate a complete business plan in minutes',
    category: 'AI Tools',
    icon: '💼',
    readTime: 5,
    description: 'Input your product details and goals. Get a full executive plan with market analysis, strategy, and financial projections.',
    tags: ['business-plan', 'strategy', 'planning'],
  },
  {
    slug: 'marketing-plan',
    title: 'AI Marketing Plan',
    subtitle: 'Generate a full 90-day marketing strategy',
    category: 'AI Tools',
    icon: '📣',
    readTime: 5,
    description: 'Pick a marketing goal and get a complete 90-day plan: channels, content strategy, budget allocation, and weekly action items — all AI-generated.',
    tags: ['marketing', 'plan', 'strategy', '90-day'],
  },
  {
    slug: 'pitch-deck',
    title: 'AI Pitch Deck Generator',
    subtitle: 'Create investor-ready pitch decks in minutes',
    category: 'AI Tools',
    icon: '🎤',
    readTime: 4,
    description: 'Generate a professional 10-slide pitch deck tailored to your business. Export to PDF or share a link with investors.',
    tags: ['pitch-deck', 'investors', 'fundraising', 'presentation'],
  },
  {
    slug: 'swot-analysis',
    title: 'AI SWOT Analysis',
    subtitle: 'AI-powered strengths, weaknesses, opportunities, threats',
    category: 'AI Tools',
    icon: '🎯',
    readTime: 4,
    description: 'Generate a data-driven SWOT analysis using your business data, competitor intelligence, and market trends — not guesswork.',
    tags: ['swot', 'strategy', 'analysis', 'planning'],
  },
  {
    slug: 'business-valuation',
    title: 'Business Valuation',
    subtitle: 'Get an AI estimate of your business worth',
    category: 'AI Tools',
    icon: '💰',
    readTime: 4,
    description: 'Enter your revenue, growth rate, and industry. Get an AI-estimated valuation range using standard multiples, with a full breakdown of factors.',
    tags: ['valuation', 'worth', 'revenue', 'multiples'],
  },
  {
    slug: 'persona-generator',
    title: 'Customer Persona Generator',
    subtitle: 'Build AI-powered buyer personas for your business',
    category: 'AI Tools',
    icon: '👤',
    readTime: 4,
    description: 'Generate detailed buyer personas based on your actual leads, customers, and industry data. Use personas to improve targeting and messaging.',
    tags: ['persona', 'buyer', 'targeting', 'marketing'],
  },
  {
    slug: 'customer-journey',
    title: 'Customer Journey Mapping',
    subtitle: 'Map every touchpoint from awareness to purchase',
    category: 'AI Tools',
    icon: '🗺️',
    readTime: 4,
    description: 'Visualize and optimize your customer\'s path from first awareness to loyal advocate. AI identifies drop-off points and suggests improvements.',
    tags: ['journey', 'funnel', 'touchpoints', 'customer-experience'],
  },

  // ── Growth ───────────────────────────────────────────────────────────────────
  {
    slug: 'campaigns',
    title: 'Email Campaigns & Drip Sequences',
    subtitle: 'Automate outreach with AI-written email sequences',
    category: 'Growth',
    icon: '📧',
    readTime: 5,
    description: 'Create drip campaigns for cold leads, follow-ups, and onboarding. AI writes the emails, you approve and send.',
    tags: ['campaigns', 'email', 'drip', 'automation'],
  },
  {
    slug: 'proposals',
    title: 'Proposals',
    subtitle: 'Create winning client proposals with AI',
    category: 'Growth',
    icon: '📋',
    readTime: 4,
    description: 'Generate professional proposals for any client. AI tailors the content based on your services and client industry.',
    tags: ['proposals', 'clients', 'sales', 'documents'],
  },
  {
    slug: 'goals',
    title: 'Goals & Targets',
    subtitle: 'Set business goals and track them in real time',
    category: 'Growth',
    icon: '📈',
    readTime: 4,
    description: 'Create revenue, leads, and content goals. The AI agent automatically tracks progress and alerts you when at risk.',
    tags: ['goals', 'targets', 'kpis', 'tracking'],
  },
  {
    slug: 'nps-feedback',
    title: 'NPS & Customer Feedback',
    subtitle: 'Measure and improve customer satisfaction',
    category: 'Growth',
    icon: '💛',
    readTime: 3,
    description: 'Run NPS surveys, collect feedback, identify detractors, and use AI insights to improve customer retention.',
    tags: ['nps', 'feedback', 'retention', 'satisfaction'],
  },

  // ── Analytics & Reports ──────────────────────────────────────────────────────
  {
    slug: 'analytics',
    title: 'Analytics Overview',
    subtitle: 'Know exactly what drives your revenue',
    category: 'Analytics & Reports',
    icon: '📊',
    readTime: 5,
    description: 'Track traffic sources, conversion rates, and revenue attribution. Understand which channels deliver the best ROI.',
    tags: ['analytics', 'attribution', 'revenue', 'reporting'],
  },
  {
    slug: 'attribution',
    title: 'Revenue Attribution',
    subtitle: 'Trace every dollar back to its source',
    category: 'Analytics & Reports',
    icon: '🔁',
    readTime: 4,
    description: 'Multi-touch attribution across channels. See first-touch, last-touch, and linear attribution for every lead and deal closed.',
    tags: ['attribution', 'revenue', 'channels', 'multi-touch'],
  },
  {
    slug: 'revenue-tracking',
    title: 'Revenue Tracking & MRR',
    subtitle: 'Track MRR, ARR, churn, and revenue trends',
    category: 'Analytics & Reports',
    icon: '💵',
    readTime: 4,
    description: 'Connect Stripe or enter revenue manually. Track Monthly Recurring Revenue, Annual Run Rate, churn rate, and monthly growth trends.',
    tags: ['revenue', 'mrr', 'arr', 'stripe', 'churn'],
  },
  {
    slug: 'metrics',
    title: 'Metrics Dashboard',
    subtitle: 'All your KPIs in one place',
    category: 'Analytics & Reports',
    icon: '🔢',
    readTime: 3,
    description: 'The Metrics dashboard shows all key performance indicators in real time: leads, pipeline value, review score, content output, and more.',
    tags: ['metrics', 'kpis', 'dashboard', 'performance'],
  },
  {
    slug: 'forecast',
    title: 'Business Forecast',
    subtitle: 'AI-predicted revenue and growth for the next 90 days',
    category: 'Analytics & Reports',
    icon: '🔮',
    readTime: 4,
    description: 'CooVex analyzes your lead pipeline, deal velocity, and historical data to forecast revenue for the next 30, 60, and 90 days.',
    tags: ['forecast', 'prediction', 'revenue', 'pipeline'],
  },
  {
    slug: 'reports',
    title: 'Reports & Exports',
    subtitle: 'Generate and share business reports',
    category: 'Analytics & Reports',
    icon: '📄',
    readTime: 3,
    description: 'Create branded PDF reports for your business, team, or clients. Choose from summary, competitor, lead, or full business reports.',
    tags: ['reports', 'pdf', 'export', 'clients'],
  },

  // ── Settings & Config ────────────────────────────────────────────────────────
  {
    slug: 'lead-scoring-settings',
    title: 'Lead Scoring Configuration',
    subtitle: 'Customize how AI scores your leads',
    category: 'Settings & Config',
    icon: '⚙️',
    readTime: 4,
    description: 'Adjust the weight of each scoring factor — job title, company size, email opens, website visits, and more. Make the score match your sales reality.',
    tags: ['scoring', 'settings', 'leads', 'configuration'],
  },

  // ── Agency ───────────────────────────────────────────────────────────────────
  {
    slug: 'agency-white-label',
    title: 'Agency & White Label',
    subtitle: 'Resell CooVex under your own brand',
    category: 'Agency',
    icon: '🏷️',
    readTime: 6,
    description: 'Set up white label branding, add client workspaces, generate reports, and manage multiple businesses from one dashboard.',
    tags: ['agency', 'white-label', 'clients', 'reseller'],
  },
]
